### ISSUE TITLE
新发布小程序逆向失败

### ISSUE THREAD

**Issue by lucybenz** [xuedingmiaojun/mp-unpack#24]
新的小程序编译版本 v0.5vv_20200413_syb_scopedata

vm.js:41
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
^^^^^^

SyntaxError: Illegal return statement
    at new Script (node:vm:99:7)
    at VM.run (/volumes/work/tool/newun/node_modules/vm2/lib/main.js:834:13)
    at /volumes/work/tool/newun/wuWxml.js:366:7
    at /volumes/work/tool/newun/wuRestoreZ.js:280:27
    at catchZ (/volumes/work/tool/newun/wuRestoreZ.js:32:5)
    at getZ (/volumes/work/tool/newun/wuRestoreZ.js:280:9)
    at /volumes/work/tool/newun/wuWxml.js:354:3
    at /volumes/work/tool/newun/wuLib.js:95:14
    at agent (/volumes/work/tool/newun/wuLib.js:64:23)

**Comment by zhangdaren** [comment]
+1
