### ISSUE TITLE
vm.js:2 SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by erekook** [xuedingmiaojun/mp-unpack#3]
`$ node wuWxapkg.js ~/xxx/_-513916267_283.wxapkg
Unpack file ~/xxx/_-513916267_283.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  2310
  dataLength:  1778803
  lastMark: 0xed

File list info:
  fileCount:  41
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
deal config ok
deal js ok
deal html ok
deal css ok
/Users/tanlongjie/Desktop/photo/_-513916267_283/app-config.json
splitJs: /Users/tanlongjie/Desktop/photo/_-513916267_283/app-service.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 config.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 utils/engine.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 utils/qqmap-wx-jssdk.min.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 utils/tool.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 utils/util.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 app.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 pages/vindex/vindex.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 pages/index/index.js
/Users/tanlongjie/Desktop/photo/_-513916267_283 pages/logs/logs.js
Splitting "/Users/tanlongjie/Desktop/photo/_-513916267_283/app-service.js" done.
Decompile ./pages/index/index.wxml...
Decompile success!
Decompile ./pages/logs/logs.wxml...
Decompile success!
Decompile ./pages/template/main.wxml...
Decompile success!
Decompile ./pages/template/templists/blankTemp.wxml...
Decompile success!
Decompile ./pages/template/templists/xiangni_sanfu0708.wxml...
Decompile success!
Decompile ./pages/template/templists/xiangni_summer0512.wxml...
Decompile success!
Decompile ./pages/template/templists/xiangni_summer0518.wxml...
Decompile success!
Decompile ./pages/template/templists/xiangni_summer0526.wxml...
Decompile success!
Decompile ./pages/template/templists/xiangni_wsh2004.wxml...
Decompile success!
Decompile ./pages/template/templists/xiangni_zsh2001.wxml...
Decompile success!
Decompile ./pages/template/tools.wxml...
Decompile success!
Decompile ./pages/vindex/vindex.wxml...
Decompile success!
vm.js:2
_C

SyntaxError: Unexpected end of input
    at new Script (vm.js:99:7)
    at VM.run (/Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/node_modules/vm2/lib/main.js:834:13)
    at /Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/wuWxss.js:243:27
    at /Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/wuLib.js:95:14
    at agent (/Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/wuLib.js:64:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)`

**Comment by xdmjun** [comment]
> `$ node wuWxapkg.js ~/xxx/_-513916267_283.wxapkg Unpack file ~/xxx/_-513916267_283.wxapkg...
> 
> Header info:
> firstMark: 0xbe
> unknownInfo: 0
> infoListLength: 2310
> dataLength: 1778803
> lastMark: 0xed
> 
> File list info:
> fileCount: 41
> Saving files...
> Unpack done.
> Split app-service.js and make up configs & wxss & wxml & wxs...
> deal config ok
> deal js ok
> deal html ok
> deal css ok
> /Users/tanlongjie/Desktop/photo/_-513916267_283/app-config.json splitJs: /Users/tanlongjie/Desktop/photo/_-513916267_283/app-service.js
> /Users/tanlongjie/Desktop/photo/_-513916267_283 config.js /Users/tanlongjie/Desktop/photo/_-513916267_283 utils/engine.js
> /Users/tanlongjie/Desktop/photo/_-513916267_283 utils/qqmap-wx-jssdk.min.js /Users/tanlongjie/Desktop/photo/_-513916267_283 utils/tool.js
> /Users/tanlongjie/Desktop/photo/_-513916267_283 utils/util.js /Users/tanlongjie/Desktop/photo/_-513916267_283 app.js
> /Users/tanlongjie/Desktop/photo/_-513916267_283 pages/vindex/vindex.js /Users/tanlongjie/Desktop/photo/_-513916267_283 pages/index/index.js
> /Users/tanlongjie/Desktop/photo/_-513916267_283 pages/logs/logs.js Splitting "/Users/tanlongjie/Desktop/photo/_-513916267_283/app-service.js" done.
> Decompile ./pages/index/index.wxml...
> Decompile success!
> Decompile ./pages/logs/logs.wxml...
> Decompile success!
> Decompile ./pages/template/main.wxml...
> Decompile success!
> Decompile ./pages/template/templists/blankTemp.wxml...
> Decompile success!
> Decompile ./pages/template/templists/xiangni_sanfu0708.wxml...
> Decompile success!
> Decompile ./pages/template/templists/xiangni_summer0512.wxml...
> Decompile success!
> Decompile ./pages/template/templists/xiangni_summer0518.wxml...
> Decompile success!
> Decompile ./pages/template/templists/xiangni_summer0526.wxml...
> Decompile success!
> Decompile ./pages/template/templists/xiangni_wsh2004.wxml...
> Decompile success!
> Decompile ./pages/template/templists/xiangni_zsh2001.wxml...
> Decompile success!
> Decompile ./pages/template/tools.wxml...
> Decompile success!
> Decompile ./pages/vindex/vindex.wxml...
> Decompile success!
> vm.js:2
> _C
> 
> SyntaxError: Unexpected end of input
> at new Script (vm.js:99:7)
> at VM.run (/Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/node_modules/vm2/lib/main.js:834:13)
> at /Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/wuWxss.js:243:27
> at /Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/wuLib.js:95:14
> at agent (/Users/tanlongjie/code/longjie/self/unpacker/wxappUnpacker/wuLib.js:64:23)
> at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)`

这个很多反馈说是微信更新了  原来的插件不适用了 解析wxss报错 暂时还没找到解决办法

**Comment by GurglingY** [comment]
等待解决方案

**Comment by Chiana1725** [comment]
打开wuWxss.js按下图修改：
![image](https://user-images.githubusercontent.com/36362974/158123210-9da54344-8c51-40ad-89db-deb81e2591a4.png)
![image](https://user-images.githubusercontent.com/36362974/158123344-eef65112-cad7-4714-b538-cb66491e228c.png)
node wuWxss.js wxapk路径，这个报错说明了执行代码时某个环节的代码没写对，按上面的图片进行修改就可以完美执行了，完美反编译

**Comment by kongmengfei** [comment]
> 打开wuWxss.js按下图修改： ![image](https://user-images.githubusercontent.com/36362974/158123210-9da54344-8c51-40ad-89db-deb81e2591a4.png) ![image](https://user-images.githubusercontent.com/36362974/158123344-eef65112-cad7-4714-b538-cb66491e228c.png) node wuWxss.js wxapk路径，这个报错说明了执行代码时某个环节的代码没写对，按上面的图片进行修改就可以完美执行了，完美反编译

后面又出错了。 node. children.each is not a function
![image](https://user-images.githubusercontent.com/57654821/201578587-4717ddc2-3093-49a4-96e3-a51f4946809d.png)
