### ISSUE TITLE
WXSS还原不了，vm.js:2 _C

### ISSUE THREAD

**Issue by qq239574** [xuedingmiaojun/mp-unpack#5]
vm.js:2 _C ^^ SyntaxError: Unexpected end of i
nput at new Script (vm.js:83:7) at VM.run (C:\Users\Administrator\AppData\Local\Pro
grams\mp-unpack\
resources\tool\node_modules\vm2\lib\main.js:834:13) at wu.get.code (C:\U
sers\Administrator\AppData\Local\Programs\mp-unpack\resources\tool\wuWxss.js:243:27) at ioLimit.runWithCb (C:\Users\Administrator\AppData\Local\Programs\mp-unpack\resources\tool\wuLib.js:95:14) at agent (C:\Users\Administrat
or\AppData\Local\Programs\mp-unpack\resources\tool\wuLib.js:64:23) at FSReqWrap.readFileAfterClos
e [as oncomplete] (i
nternal/fs/read_file_cont
ext.js:53:3)

**Comment by xdmjun** [comment]
这个问题是wxss解析报错导致，暂时还没解决------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;qq239574&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月21日(星期二) 晚上7:35
收件人:&nbsp;&quot;xuedingmiaojun/mp-unpack&quot;<mp-unpack@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xuedingmiaojun/mp-unpack] WXSS还原不了，vm.js:2 _C (#5)

**Comment by jianqiao0313** [comment]
+1

**Comment by Fizzyi** [comment]
+1 我也遇见了这个情况

**Comment by GurglingY** [comment]
+1 求解决方法

**Comment by jianqiao0313** [comment]
如果不考虑css样式的话，可以在wuWxss.js278行直接return。可以正常解包
https://github.com/xuedingmiaojun/mp-unpack/issues/4#issuecomment-662363512

**Comment by chic2008** [comment]
+1 求解决方法

**Comment by wuokong** [comment]
咋样了？？？？？？？？如何解决的
